/**
 * @typedef {[string, string, 'text' | 'textarea' | 'number'] | [string, string, 'select', string[]]} NPCField
 * @typedef {{ title: string, fields: NPCField[], combat?: boolean }} NPCSection
 */

/** @type {NPCSection[]} */
export const sections = [
 {title:'Basic Information',fields:[['name','Character name','text'],['nicknames','Nicknames or titles','text'],['pronouns','Pronouns','text'],['age','Age','text'],['species','Species or lineage','text'],['homeland','Homeland','text'],['region','Region','text'],['culture','Culture','text'],['class_name','Class','text'],['subclass','Subclass','text'],['level','Character level','number'],['alignment','Alignment','text'],['occupation','Occupation or role','text'],['faction','Faction or organization','text'],['campaign','Campaign setting','text']]},
 {title:'Appearance',fields:[['physical_description','Physical description','textarea'],['clothing_equipment','Clothing and equipment','textarea'],['distinguishing_features','Distinguishing features','textarea'],['image_prompt','Image-generation description','textarea'],['art_style','Approved art style','text']]},
 {title:'Personality',fields:[['personality_traits','Personality traits','textarea'],['ideals','Ideals','textarea'],['bonds','Bonds','textarea'],['flaws','Flaws','textarea'],['likes_dislikes','Likes and dislikes','textarea'],['fears','Fears','textarea'],['mannerisms','Habits and mannerisms','textarea'],['humor','Sense of humor','text'],['temperament','Emotional temperament','text'],['social_behavior','Social behavior','textarea']]},
 {title:'Voice & Communication',fields:[['speaking_style','Speaking style','textarea'],['vocabulary','Vocabulary level','text'],['accent','Accent or cultural influence','text'],['expressions','Common expressions','textarea'],['avoided_topics','Topics the NPC avoids','textarea'],['conditional_information','Conditionally revealed information','textarea']]},
 {title:'History & Motivation',fields:[['backstory','Backstory','textarea'],['relationships','Important relationships','textarea'],['goals','Personal goals','textarea'],['objectives','Short-term objectives','textarea'],['secrets','Secrets (DM only)','textarea'],['internal_conflicts','Internal conflicts','textarea'],['current_problems','Current problems','textarea'],['party_stance_reasons','Reasons for helping or opposing the party','textarea']]},
 {title:'Campaign Role',fields:[['role','NPC role','select',['Ally','Enemy','Rival','Merchant','Quest giver','Companion','Authority figure','Informant','Neutral']],['location','Current location','text'],['services','Services offered','textarea'],['quests_rumors','Quests or rumors available','textarea'],['world_knowledge','Knowledge about the campaign world','textarea'],['party_relationship','Relationship with player characters','textarea'],['initial_attitude','Initial attitude toward the party','text'],['ally_status','Ally or enemy status','select',['ally','enemy','neutral','unknown']]]},
 {title:'Game Statistics',combat:true,fields:[['armor_class','Armor Class','number'],['hit_points','Hit Points','number'],['speed','Speed','text'],['ability_scores','Ability scores','textarea'],['saving_throws','Saving throws','textarea'],['skills','Skills','textarea'],['senses','Senses','textarea'],['languages','Languages','text'],['proficiency_bonus','Proficiency bonus','number'],['challenge_rating','Challenge Rating','text'],['actions','Actions','textarea'],['bonus_actions','Bonus actions','textarea'],['reactions','Reactions','textarea'],['traits','Traits','textarea'],['spells','Spells','textarea'],['equipment','Equipment','textarea'],['damage_defenses','Resistances, immunities, vulnerabilities','textarea']]}
];

export const initialNPC={mode:'roleplay',archived:false,ally_status:'unknown',level:1,npc_build_type:'',power_level:'',ruleset:'',portrait_candidates:[],portrait_variants:[],primary_traits:[],major_life_events:[]};
