import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Archive, Copy, Download, MessageCircle, Pencil, RotateCcw, Trash2, FileText } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import PageHeader from '@/components/PageHeader';
import { Image } from '@/components/ui/image';
import CampaignAssign from '@/components/npc/CampaignAssign';
import { sections } from '@/lib/npcFields';
import NavControls from '@/components/NavControls';
import ResetDialog from '@/components/npc/ResetDialog';
import AppearancePanel from '@/components/npc/AppearancePanel';
export default function NPCDetail(){const {id}=useParams(),nav=useNavigate(),[npc,setNpc]=useState(null),[resetOpen,setResetOpen]=useState(false);const reload=()=>base44.entities.NPC.get(id).then(setNpc);useEffect(()=>{base44.entities.NPC.get(id).then(setNpc)},[id]);if(!npc)return <div className="p-8 text-muted-foreground">Opening character record…</div>;const remove=async()=>{await base44.entities.NPC.delete(id);nav('/library')};const exportNPC=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(npc,null,2)],{type:'application/json'}));a.download=`${npc.name}.json`;a.click()};return <div className="p-5 sm:p-8"><NavControls fallback="/library"/><PageHeader eyebrow={`${npc.species||'Unknown lineage'} · ${npc.role||'NPC'}`} title={npc.name} description={[npc.class_name,npc.alignment,npc.campaign].filter(Boolean).join(' · ')} action={<Link to={`/roleplay/${id}`} className="flex items-center gap-2 rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-brand-foreground"><MessageCircle size={16}/>Enter roleplay</Link>}/><div className="mb-7 flex flex-wrap gap-2"><Link to={`/sheet/${id}`} className="tool"><FileText/>View Sheet</Link><Link to={`/edit/${id}`} className="tool"><Pencil/>Edit</Link><Link to={`/create?duplicate=${id}`} className="tool"><Copy/>Duplicate</Link><button onClick={()=>base44.entities.NPC.update(id,{archived:!npc.archived}).then(x=>setNpc(x))} className="tool"><Archive/>{npc.archived?'Restore':'Archive'}</button><button onClick={exportNPC} className="tool"><Download/>Export</button><button onClick={()=>setResetOpen(true)} className="tool"><RotateCcw/>Reset</button><button onClick={remove} className="tool text-destructive"><Trash2/>Delete</button></div><ResetDialog npc={npc} open={resetOpen} onOpenChange={setResetOpen} onDone={reload}/><CampaignAssign npc={npc} onAssigned={setNpc}/>{npc.portrait_url&&<Image src={npc.portrait_url} alt={`Portrait of ${npc.name}`} className="mb-6 h-72 w-full rounded-2xl border border-border sm:w-72"/>}<AppearancePanel npc={npc} onUpdated={reload}/>
<div className="grid gap-5 lg:grid-cols-2">{sections.filter(s=>(npc.mode==='combat'||!s.combat)&&s.title!=='Appearance').map(s=><section key={s.title} className="rounded-2xl border border-border bg-card p-5"><h2 className="font-serif text-xl text-brand">{s.title}</h2><dl className="mt-4 space-y-3">{s.fields.filter(f=>npc[f[0]]!==undefined&&npc[f[0]]!=='').map(f=><div key={f[0]}><dt className="text-xs uppercase tracking-wider text-muted-foreground">{f[1]}</dt><dd className="mt-1 whitespace-pre-wrap text-sm leading-6 text-foreground">{String(npc[f[0]])}</dd></div>)}</dl></section>)}</div></div>}